### ISSUE TITLE
swift 2.1 support

### ISSUE THREAD

**Issue by uknowmeright** [johncosch/TIPBadgeManager#5]
the code is broken on the latest version of swift (2.1).
it gives an error at this line:

`bv!.setTranslatesAutoresizingMaskIntoConstraints(false)`

please add support for swift 2.1

**Comment by johncosch** [comment]
@uknowmeright thanks for addressing this. I haven't been doing a great job of maintaining this repo but, I'll make sure I get this issue sorted out in the coming days.

**Comment by johncosch** [comment]
@uknowmeright I can't seem to replicate this error. If you're still using version 0.2.1 then I would try updating to version 0.3.0. That version should have swift 2.0 and 2.1 compatibility. If your already on the latest version would you mind posting the full error your getting? In the meantime I'll update the README to reflect instructions for the latest version. Thanks!

**Comment by johncosch** [comment]
I'm closing this issue because these errors should not persist in version 0.3.0.
