### ISSUE TITLE
Please add framework scheme

### ISSUE THREAD

**Issue by paulz** [johncosch/TIPBadgeManager#7]
Thank you for awesome project!

When trying to install with https://github.com/Carthage/Carthage, we are getting this error:

```
*** Skipped building TIPBadgeManager due to the error:
Dependency "TIPBadgeManager" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/johncosch/TIPBadgeManager/issues/new
```

Would it be possible to add a framework scheme?

**Comment by johncosch** [comment]
Thank you for the compliments and PR! Sorry I couldn't get to this sooner. The PR wasn't working for me so I had to revoke it and push the changes up on my own. It should be working with Carthage now, please don't hesitate to submit another issue if you have any other problems. Thanks again!
