### ISSUE TITLE
TIPBadgeManager on UISegmentedControl

### ISSUE THREAD

**Issue by BorisNikolic** [johncosch/TIPBadgeManager#9]
If you want to use this control on UISegmentedControl for each of the UISegments, this is the way:

```
  TIPBadgeManager.sharedInstance.addBadgeSuperview("someViewName", view: self.segmentedControl.subviews[1])
  TIPBadgeManager.sharedInstance.setBadgeValue("someViewName", value: 2)
```

If you have UISegmentedControl with 3 segments, this will put it on the middle one.

HINT - If you want to put it on the last one (all the way right) you should target .subviews[0], and all the way left(first UISegment) .subviews[2]

Take care!

**Comment by johncosch** [comment]
@SirobChilokin thanks for filing this issue! I'm sure this will come in handy for someone.
